[git]
username = "arctan1024"
email = "jaexentan@gmail.com"

[omz]
# https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
theme = "bira"
# https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins
plugins = ["git", "pass", "zoxide"]

[env]
# Keep these envs unchanged!
DISABLE_MAGIC_FUNCTIONS = "true"
HOMEBREW_BUNDLE_FILE = "~/.config/homebrew/Brewfile"
HOMEBREW_NO_AUTO_UPDATE = "true"
ELECTRON_OZONE_PLATFORM_HINT = "auto"

[alias]
hm = "home-manager"
hms = "home-manager switch --impure"
brewdump = "brew bundle dump --cask --mas --tap --describe --force"
brewup = "brew bundle install"
nixgc = "nix-collect-garbage --delete-old"
ll = "ls -alh"

[home.file]
".ssh/id_ed25519.pub" = { text = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID3JKBJ2bthxg4cpbYOEjy7x0xkiyK83vC72bHue70dj jaexentan@gmail.com" }

[nix]
# https://search.nixos.org/packages
packages = ["fastfetch", "lazygit", "pass", "tldr", "tree", "zoxide"]
